name: Build

on:
    push:
        branches: [ duckart-dev-july-6 ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        strategy:
            fail-fast: true
            matrix:
                os: [ ubuntu-latest, macos-latest ]
                java: [ '8', '11' ]
        runs-on: ${{ matrix.os }}
        name: Running Java ${{ matrix.java }} on ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK ${{ matrix.java }}
                uses: actions/setup-java@v1
                with:
                    java-version: ${{ matrix.java }}
            -   name: Test code
                run: mvn -B -q test -D'logging.level.edu.hawaii.its.filedrop=OFF' -D'logging.level.org.springframework=ERROR' -D'spring.main.banner-mode=off' -D'test=*Test'
