name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        platform: [ macos-latest ]
    runs-on: ${{ matrix.platform }}
    name: Running Java ${{ matrix.java }} compile
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Compile code
      run: mvn -q test -D'logging.level.edu.hawaii.its.filedrop=OFF' -D'logging.level.org.springframework=ERROR' -D'spring.main.banner-mode=off' -D'test=DatesTest'